// AUTO-GENERATED by props/tools/generate_style_schema.py. DO NOT EDIT.
export const generatedStyleSchema = {
  "version": 1,
  "cores": {
    "main": {
      "core_type": "main",
      "description": "Primary blade style core"
    }
  },
  "sharedCore": {
    "main": {
      "params": [
        {
          "key": "base_color",
          "arg_symbol": "BASE_COLOR_ARG"
        },
        {
          "key": "alt_color",
          "arg_symbol": "ALT_COLOR_ARG"
        },
        {
          "key": "style_option",
          "arg_symbol": "STYLE_OPTION_ARG"
        },
        {
          "key": "ignition_option",
          "arg_symbol": "IGNITION_OPTION_ARG"
        },
        {
          "key": "ignition_time",
          "arg_symbol": "IGNITION_TIME_ARG"
        },
        {
          "key": "ignition_delay",
          "arg_symbol": "IGNITION_DELAY_ARG"
        },
        {
          "key": "ignition_color",
          "arg_symbol": "IGNITION_COLOR_ARG"
        },
        {
          "key": "ignition_power_up",
          "arg_symbol": "IGNITION_POWER_UP_ARG"
        },
        {
          "key": "blast_color",
          "arg_symbol": "BLAST_COLOR_ARG"
        },
        {
          "key": "clash_color",
          "arg_symbol": "CLASH_COLOR_ARG"
        },
        {
          "key": "lockup_color",
          "arg_symbol": "LOCKUP_COLOR_ARG"
        },
        {
          "key": "lockup_position",
          "arg_symbol": "LOCKUP_POSITION_ARG"
        },
        {
          "key": "drag_color",
          "arg_symbol": "DRAG_COLOR_ARG"
        },
        {
          "key": "drag_size",
          "arg_symbol": "DRAG_SIZE_ARG"
        },
        {
          "key": "lb_color",
          "arg_symbol": "LB_COLOR_ARG"
        },
        {
          "key": "stab_color",
          "arg_symbol": "STAB_COLOR_ARG"
        },
        {
          "key": "melt_size",
          "arg_symbol": "MELT_SIZE_ARG"
        },
        {
          "key": "swing_color",
          "arg_symbol": "SWING_COLOR_ARG"
        },
        {
          "key": "swing_option",
          "arg_symbol": "SWING_OPTION_ARG"
        },
        {
          "key": "emitter_color",
          "arg_symbol": "EMITTER_COLOR_ARG"
        },
        {
          "key": "emitter_size",
          "arg_symbol": "EMITTER_SIZE_ARG"
        },
        {
          "key": "preon_color",
          "arg_symbol": "PREON_COLOR_ARG"
        },
        {
          "key": "preon_option",
          "arg_symbol": "PREON_OPTION_ARG"
        },
        {
          "key": "preon_size",
          "arg_symbol": "PREON_SIZE_ARG"
        },
        {
          "key": "retraction_option",
          "arg_symbol": "RETRACTION_OPTION_ARG"
        },
        {
          "key": "retraction_time",
          "arg_symbol": "RETRACTION_TIME_ARG"
        },
        {
          "key": "retraction_delay",
          "arg_symbol": "RETRACTION_DELAY_ARG"
        },
        {
          "key": "retraction_color",
          "arg_symbol": "RETRACTION_COLOR_ARG"
        },
        {
          "key": "retraction_cool_down",
          "arg_symbol": "RETRACTION_COOL_DOWN_ARG"
        },
        {
          "key": "postoff_color",
          "arg_symbol": "POSTOFF_COLOR_ARG"
        },
        {
          "key": "off_color",
          "arg_symbol": "OFF_COLOR_ARG"
        },
        {
          "key": "off_option",
          "arg_symbol": "OFF_OPTION_ARG"
        }
      ]
    },
    "secondary": {
      "params": [
        {
          "key": "alt_color2",
          "arg_symbol": "ALT_COLOR2_ARG"
        },
        {
          "key": "alt_color3",
          "arg_symbol": "ALT_COLOR3_ARG"
        },
        {
          "key": "style_option2",
          "arg_symbol": "STYLE_OPTION2_ARG"
        },
        {
          "key": "style_option3",
          "arg_symbol": "STYLE_OPTION3_ARG"
        },
        {
          "key": "ignition_option2",
          "arg_symbol": "IGNITION_OPTION2_ARG"
        },
        {
          "key": "retraction_option2",
          "arg_symbol": "RETRACTION_OPTION2_ARG"
        }
      ]
    }
  },
  "styles": [
    {
      "name": "standard",
      "core": "main",
      "parser_name": "ini2_standard",
      "params": [
        {
          "key": "style_option",
          "arg_symbol": "STYLE_OPTION_ARG"
        },
        {
          "key": "swing_option",
          "arg_symbol": "SWING_OPTION_ARG"
        },
        {
          "key": "ignition_option",
          "arg_symbol": "IGNITION_OPTION_ARG"
        },
        {
          "key": "retraction_option",
          "arg_symbol": "RETRACTION_OPTION_ARG"
        }
      ]
    },
    {
      "name": "audioflicker",
      "core": "main",
      "parser_name": "ini2_audioflicker",
      "include_secondary": true,
      "params": [
        {
          "key": "style_option",
          "arg_symbol": "STYLE_OPTION_ARG"
        },
        {
          "key": "swing_option",
          "arg_symbol": "SWING_OPTION_ARG"
        },
        {
          "key": "ignition_option",
          "arg_symbol": "IGNITION_OPTION_ARG"
        },
        {
          "key": "retraction_option",
          "arg_symbol": "RETRACTION_OPTION_ARG"
        }
      ]
    }
  ]
} as const;
